class AddNoserversGames < ActiveRecord::Migration
  def self.up
    gameno102 = Game.create(
      :name => "傲世三国online",
      :official_web => "www.aoshionline.com",
      :sale_date => "2006-2-22",
      :company => "目标软件",
      :agent => "目标软件",
      :no_races => true,
      :description => "国产3D大型角色扮演游戏")
    gameno102.tag_list = "热血, 中国玄幻, 道具收费, 即时战斗, 3D"
    gameno103 = Game.create(
      :name => "傲神传",
      :official_web => "http://www.aszol.com/",
      :sale_date => "2008-4-3",
      :company => "厦门荣耀科艺",
      :agent => "安徽澳澜科技",
      :no_races => true,
      :description => "国产3D大型角色扮演游戏")
    gameno103.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno104 = Game.create(
      :name => "霸王",
      :official_web => "http://ac.sdo.com/web2.0/",
      :sale_date => "2006-6-25",
      :company => "韩国NHN",
      :agent => "盛大网络",
      :no_races => true,
      :description => "韩国2D大型角色扮演游戏")
    gameno104.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno105 = Game.create(
      :name => "宝宝总动员",
      :official_web => "http://baobao.gtgame.com.cn/",
      :sale_date => "2008-3-18",
      :company => "SonoKong",
      :agent => "光通",
      :no_races => true,
      :description => "益智休闲游戏")
    gameno105.tag_list = "Q版, 休闲, 道具收费, 益智, 3D"
    gameno106 = Game.create(
      :name => "布鲁布鲁卡卡",
      :official_web => "http://www.blblkk.com/",
      :sale_date => "2007-5-17",
      :company => "道道通网络",
      :agent => "亿噢网络",
      :no_races => true,
      :description => "休闲网络游戏")
    gameno106.tag_list = "Q版, 休闲, 道具收费, 益智, 3D"
    gameno107 = Game.create(
      :name => "传说online",
      :official_web => "http://www.saga3d.com/",
      :sale_date => "2005-3-30",
      :company => "成都锦天科技",
      :agent => "成都锦天科技",
      :no_races => true,
      :description => "国产3D大型角色扮演游戏")
    gameno107.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno108 = Game.create(
      :name => "超级武林大富翁",
      :official_web => "http://wl.hanghai.com/index.asp",
      :sale_date => "2007-8-22",
      :company => "游戏蜗牛",
      :agent => "游戏蜗牛",
      :no_races => true,
      :description => "休闲回合制角色扮演游戏")
    gameno108.tag_list = "Q版, 休闲, 道具收费, 回合制战斗, 2D"
    gameno109 = Game.create(
      :name => "宠物小精灵",
      :official_web => "http://www.xjlgame.com/",
      :sale_date => "2009-9-10",
      :company => "暴雨娱乐",
      :agent => "暴雨娱乐",
      :no_races => true,
      :description => "Q版3D角色扮演游戏")
    gameno109.tag_list = "Q版, 玄幻, 道具收费, 即时战斗, 3D"
    gameno110 = Game.create(
      :name => "苍天",
      :official_web => "http://ct.sdo.com/project/guide0906/default.html",
      :sale_date => "2008-12-25",
      :company => "娱美德（Wemade）",
      :agent => "盛大网络",
      :no_races => true,
      :description => "3D三国类大型角色扮演游戏")
    gameno110.tag_list = "热血, 武侠, 道具收费, 即时战斗, 3D"
    gameno111 = Game.create(
      :name => "宠物森林",
      :official_web => "http://mf.9you.com/",
      :sale_date => "2008-6-25",
      :company => "久游",
      :agent => "久游",
      :no_races => true,
      :no_professions => true,
      :description => "3D回合制角色扮演游戏")
    gameno111.tag_list = "Q版, 休闲, 道具收费, 回合制战斗, 3D"
    gameno112 = Game.create(
      :name => "超级跑跑",
      :official_web => "http://pao.sdo.com/web2.0/home/index.asp",
      :sale_date => "2007-6-27",
      :company => "Rhaon",
      :agent => "盛大网络",
      :no_races => true,
      :no_professions => true,
      :description => "3D休闲赛车游戏")
    gameno112.tag_list = "休闲, 赛车, 道具收费, 赛车, 3D"
    gameno113 = Game.create(
      :name => "春秋Q传",
      :official_web => "http://cq.xoyo.com/",
      :sale_date => "2007-9-20",
      :company => "成都亚丁",
      :agent => "金山西山居",
      :no_races => true,
      :description => "3D大型回合制角色扮演游戏")
    gameno113.tag_list = "Q版, 中国玄幻, 道具收费, 回合制战斗, 3D"
    gameno114 = Game.create(
      :name => "冲锋online",
      :official_web => "http://www.rushcn.com/",
      :sale_date => "2007-7-20",
      :company => "softnyx",
      :agent => "戏杰环球",
      :no_races => true,
      :description => "3D大型角色扮演游戏")
    gameno114.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno115 = Game.create(
      :name => "苍穹",
      :official_web => "http://cq.wtgame.net",
      :sale_date => "2009-9-28",
      :company => "问天科技",
      :agent => "问天科技",
      :no_races => true,
      :description => "3D大型角色扮演游戏")
    gameno115.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno116 = Game.create(
      :name => "大富翁online",
      :official_web => "http://rich.9you.com/",
      :sale_date => "2007-11-15",
      :company => "久游",
      :agent => "久游",
      :no_races => true,
      :no_professions => true,
      :description => "休闲益智")
    gameno116.tag_list = "Q版, 休闲, 道具收费, 大富翁, 3D"
    gameno117 = Game.create(
      :name => "大话战国Online",
      :official_web => "http://www.zg.mop.com/",
      :sale_date => "2007-4-5",
      :company => "网游数码",
      :agent => "猫扑网",
      :no_races => true,
      :description => "Q版2D角色扮演游戏")
    gameno117.tag_list = "Q版, 中国玄幻, 道具收费, 即时战斗, 2D"
    gameno118 = Game.create(
      :name => "大唐风云",
      :official_web => "http://www.dtfy.cn/",
      :sale_date => "2006-2-13",
      :company => "杭州天畅",
      :agent => "杭州天畅",
      :no_races => true,
      :description => "3D大型角色扮演游戏")
    gameno118.tag_list = "热血, 奇幻, 时间收费, 即时战斗, 3D"
    gameno119 = Game.create(
      :name => "迪士尼魔幻飞板",
      :official_web => "http://dmb.sdo.com/web2.0/home/index.asp",
      :sale_date => "",
      :company => "迪士尼",
      :agent => "盛大网络",
      :no_races => true,
      :no_professions => true,
      :description => "3D休闲竞速游戏")
    gameno119.tag_list = "Q版, 竞速, 道具收费, 休闲, 3D"
    gameno120 = Game.create(
      :name => "大话仙剑",
      :official_web => "http://www.xianjian8.com/",
      :sale_date => "2009-9-10",
      :company => "逸海情天",
      :agent => "阿比酷",
      :no_races => true,
      :description => "3D大型角色扮演游戏")
    gameno120.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno121 = Game.create(
      :name => "帝国传奇",
      :official_web => "http://www.el-g.com/",
      :sale_date => "2006-12-26",
      :company => "杭州二元",
      :agent => "杭州二元",
      :no_races => true,
      :no_professions => true,
      :description => "3D大型角色扮演游戏")
    gameno121.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno122 = Game.create(
      :name => "捣蛋基地",
      :official_web => "http://dd.18day.com/index.html",
      :sale_date => "2008-10-9",
      :company => "台州精业",
      :agent => "台州精业",
      :no_races => true,
      :description => "3D回合制角色扮演游戏")
    gameno122.tag_list = "Q版, 奇幻, 道具收费, 回合制战斗, 3D"
    gameno123 = Game.create(
      :name => "大明龙权",
      :official_web => "http://dm.qq.com/",
      :sale_date => "2009-7-8",
      :company => "佳游网络",
      :agent => "腾讯科技",
      :no_races => true,
      :description => "2D大型角色扮演游戏")
    gameno123.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno124 = Game.create(
      :name => "地牢骑士团",
      :official_web => "http://dnk.skdaren.com/",
      :sale_date => "2009-9-16",
      :company => "武汉盛科网络",
      :agent => "武汉盛科网络",
      :no_races => true,
      :description => "3D大型角色扮演游戏")
    gameno124.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno125 = Game.create(
      :name => "蛋清",
      :official_web => "http://www.7uif.com/",
      :sale_date => "2009-9-22",
      :company => "奇人快游网络",
      :agent => "奇人快游网络",
      :no_races => true,
      :description => "Q版3D大型角色扮演游戏")
    gameno125.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 3D"
    gameno126 = Game.create(
      :name => "2061",
      :official_web => "http://2061.gameyj.com/",
      :sale_date => "2009-11-7",
      :company => "亿佳网络技术",
      :agent => "亿佳网络技术",
      :no_races => true,
      :description => "3D大型角色扮演游戏")
    gameno126.tag_list = "热血, 科幻, 道具收费, 即时战斗, 2D"
    gameno127 = Game.create(
      :name => "风云",
      :official_web => "http://www.fy0.cn/",
      :sale_date => "2006-12-15",
      :company => "锦天科技",
      :agent => "锦天科技",
      :no_races => true,
      :description => "3D大型角色扮演游戏")
    gameno127.tag_list = "热血, 中国玄幻, 道具收费, 即时战斗, 3D"
    gameno128 = Game.create(
      :name => "封神榜",
      :official_web => "http://fs.xoyo.com/",
      :sale_date => "2004年12月16日",
      :company => "金山西山居",
      :agent => "金山西山居",
      :no_races => true,
      :description => "2D大型角色扮演游戏")
    gameno128.tag_list = "热血, 中国玄幻, 时间收费, 道具收费, 即时战斗, 2D"
    gameno129 = Game.create(
      :name => "凤舞天骄",
      :official_web => "http://fw.object.com.cn/",
      :sale_date => "2006-7-20",
      :company => "目标软件",
      :agent => "目标软件",
      :no_races => true,
      :description => "2D大型角色扮演游戏")
    gameno129.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno130 = Game.create(
      :name => "飞天风云",
      :official_web => "http://ft.xoyo.com/",
      :sale_date => "2008-3-1",
      :company => "致雄网络",
      :agent => "金山西山居",
      :no_races => true,
      :description => "3D大型角色扮演游戏")
    gameno130.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno131 = Game.create(
      :name => "疯狂飚车",
      :official_web => "http://cs.9you.com",
      :sale_date => "2008-3-20",
      :company => "久游",
      :agent => "久游",
      :no_races => true,
      :no_professions => true,
      :description => "3D赛车竞速游戏")
    gameno131.tag_list = "竞速, 赛车, 道具收费, 仿真, 3D"
    gameno132 = Game.create(
      :name => "疯狂派对",
      :official_web => "http://www.ppcrazy.com/",
      :sale_date => "2007-5-24",
      :company => "宇皇",
      :agent => "腾仁信息",
      :no_races => true,
      :no_professions => true,
      :description => "2D休闲社区类")
    gameno132.tag_list = "轻松, 休闲, 道具收费, 社区, 2D"
    gameno133 = Game.create(
      :name => "反恐行动",
      :official_web => "http://xd.xoyo.com/",
      :sale_date => "2008-4-22",
      :company => "鲸彩工作室",
      :agent => "金山西山居",
      :no_races => true,
      :no_professions => true,
      :description => "3D第一人称枪战游戏")
    gameno133.tag_list = "热血, 道具收费, 第一人称, 枪战, 3D"
    gameno134 = Game.create(
      :name => "富甲西游",
      :official_web => "http://fj.163.com/",
      :sale_date => "2007-4-11",
      :company => "网易",
      :agent => "网易",
      :no_races => true,
      :no_professions => true,
      :description => "2D休闲大富翁类游戏")
    gameno134.tag_list = "Q版, 休闲, 道具收费, 大富翁, 2D"
    gameno135 = Game.create(
      :name => "疯狂弹头",
      :official_web => "http://www.leqigame.com/",
      :sale_date => "",
      :company => "首领科技",
      :agent => "广州乐奇",
      :no_races => true,
      :no_professions => true,
      :description => "3D枪火休闲游戏")
    gameno135.tag_list = "轻松, 休闲, 道具收费, 射击, 3D"
    gameno136 = Game.create(
      :name => "封印传说",
      :official_web => "http://fy.lqn.cn/index.jsp",
      :sale_date => "2007-11-15",
      :company => "雷穹网络科技",
      :agent => "雷穹网络科技",
      :no_races => true,
      :stop_running => true,
      :description => "3D大型角色扮演游戏")
    gameno136.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno137 = Game.create(
      :name => "反恐精英online",
      :official_web => "http://csol.tiancity.com/homepage/v3/",
      :sale_date => "2008-10-21",
      :company => "Nexon",
      :agent => "世纪天成",
      :no_races => true,
      :no_professions => true,
      :description => "3D第一人称射击游戏")
    gameno137.tag_list = "热血, 道具收费, 第一人称, 射击, 3D"
    gameno138 = Game.create(
      :name => "烽火情缘2",
      :official_web => "http://fh2.18day.com/home/index.aspx",
      :sale_date => "2008-12-29",
      :company => "",
      :agent => "",
      :no_races => true,
      :description => "3D大型角色扮演游戏")
    gameno138.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno139 = Game.create(
      :name => "纷争",
      :official_web => "http://www.fzplay.com.cn/",
      :sale_date => "2009-7-8",
      :company => "智信恒",
      :agent => "智信恒",
      :no_races => true,
      :description => "3D大型角色扮演游戏")
    gameno139.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno140 = Game.create(
      :name => "烽火情缘",
      :official_web => "http://fh.18day.com/index.aspx?fromurl=&iLevel=2&counterNumKey=click",
      :sale_date => "2007-2-18",
      :company => "",
      :agent => "",
      :no_races => true,
      :description => "2D大型角色扮演游戏")
    gameno140.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno141 = Game.create(
      :name => "光线飞车",
      :official_web => "http://rc.9you.com/index.shtml",
      :sale_date => "2007-11-8",
      :company => "J2M",
      :agent => "久游网",
      :no_races => true,
      :no_professions => true,
      :description => "3D竞速类角色扮演游戏")
    gameno141.tag_list = "热血, 竞速, 道具收费, 赛车, 3D"
    gameno142 = Game.create(
      :name => "光之国度",
      :official_web => "http://shine.gtgame.com.cn/index.html",
      :sale_date => "2007-9-20",
      :company => "ARAGON",
      :agent => "光通通信",
      :no_races => true,
      :description => "Q版3D大型角色扮演游戏")
    gameno142.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 3D"
    gameno143 = Game.create(
      :name => "功夫小子",
      :official_web => "http://kk.sdo.com/web3/index/xinshou.htm",
      :sale_date => "2007-12-22",
      :company => "盛大网络",
      :agent => "盛大网络",
      :no_races => true,
      :no_professions => true,
      :description => "3D格斗类休闲游戏")
    gameno143.tag_list = "热血, 格斗, 道具收费, 休闲, 3D"
    gameno144 = Game.create(
      :name => "鬼吹灯外传",
      :official_web => "http://gui.sdo.com/web1/home/index.asp",
      :sale_date => "2009-8-13",
      :company => "麦石信息",
      :agent => "盛大网络",
      :no_races => true,
      :description => "横板格斗角色扮演游戏")
    gameno144.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno145 = Game.create(
      :name => "古域",
      :official_web => "http://gy.changyou.com/",
      :sale_date => "2009-9-24",
      :company => "九艺",
      :agent => "搜狐畅游",
      :no_races => true,
      :description => "3D大型角色扮演游戏")
    gameno145.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno146 = Game.create(
      :name => "华夏online",
      :official_web => "http://www.hxfree.com/hxfree.html",
      :sale_date => "2004-12-30",
      :company => "网域",
      :agent => "网域",
      :no_races => true,
      :description => "2D大型角色扮演游戏")
    gameno146.tag_list = "热血, 奇幻, 时间收费, 道具收费, 即时战斗, 2D"
    gameno147 = Game.create(
      :name => "海盗王online",
      :official_web => "http://hdwonline.moliyo.com/",
      :sale_date => "2005-8-6",
      :company => "摩力游",
      :agent => "摩力游",
      :no_races => true,
      :description => "Q版3D大型角色扮演游戏")
    gameno147.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 3D"
    gameno148 = Game.create(
      :name => "滑轮风",
      :official_web => "http://xplay.chinagames.net/",
      :sale_date => "2008-11-18",
      :company => "KTH/MansAmusement",
      :agent => "中国游戏中心",
      :no_races => true,
      :no_professions => true,
      :description => "2D动作竞速游戏")
    gameno148.tag_list = "轻松, 休闲, 道具收费, 竞速, 2D"
    gameno149 = Game.create(
      :name => "哼哼哈嘿",
      :official_web => "http://www.tiancity.com/homepage/",
      :sale_date => "2008-2-26",
      :company => "NDOORS",
      :agent => "世纪天成",
      :no_races => true,
      :no_professions => true,
      :description => "3D休闲格斗游戏")
    gameno149.tag_list = "轻松, 休闲, 道具收费, 格斗, 3D"
    gameno150 = Game.create(
      :name => "幻想学园online",
      :official_web => "http://fc.runup.cn/eventsite/",
      :sale_date => "2008-8-5",
      :company => "宏龙网络",
      :agent => "千峰云起",
      :no_races => true,
      :description => "Q版3D大型角色扮演游戏")
    gameno150.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno151 = Game.create(
      :name => "合金弹头OL",
      :official_web => "http://www.metalslugzero.com/",
      :sale_date => "",
      :company => "Dragonfly",
      :agent => "",
      :no_races => true,
      :no_professions => true,
      :description => "3D大型角色扮演游戏")
    gameno151.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno152 = Game.create(
      :name => "幻想大陆",
      :official_web => "http://www.fantasyearth.com.cn/",
      :sale_date => "2007-12-7",
      :company => "SQUARE ENIX",
      :agent => "易玩通",
      :no_races => true,
      :description => "3D大型角色扮演游戏")
    gameno152.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno153 = Game.create(
      :name => "黄易群侠传online",
      :official_web => "http://hy.iyoyo.com.cn/",
      :sale_date => "2007-8-3",
      :company => "中华网龙",
      :agent => "悠游网",
      :no_races => true,
      :description => "国产3D大型角色扮演游戏")
    gameno153.tag_list = "热血, 中国玄幻, 道具收费, 即时战斗, 3D"
    gameno154 = Game.create(
      :name => "幻灵游侠",
      :official_web => "http://hl.91.com/",
      :sale_date => "2004-4-10",
      :company => "天晴数码",
      :agent => "网龙",
      :no_races => true,
      :no_professions => true,
      :description => "2D回合制角色扮演游戏")
    gameno154.tag_list = "轻松, 奇幻, 道具收费, 回合制战斗, 2D"
    gameno155 = Game.create(
      :name => "合金战纪",
      :official_web => "http://hejin.ddtone.com/",
      :sale_date => "2007-9-19",
      :company => "韩国CYKAN",
      :agent => "道道通",
      :no_races => true,
      :description => "3D横板角色扮演游戏")
    gameno155.tag_list = "Q版, 奇幻, 道具收费, 横板战斗, 3D"
    gameno156 = Game.create(
      :name => "海之乐章",
      :official_web => "http://intro.yoyigame.com/index.action",
      :sale_date => "2007-4-1",
      :company => "游艺",
      :agent => "游艺",
      :no_races => true,
      :description => "Q版2D角色扮演游戏")
    gameno156.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 2D"
    gameno157 = Game.create(
      :name => "海战传奇",
      :official_web => "http://nl.9hgame.com/",
      :sale_date => "2009-7-21",
      :company => "九合天下",
      :agent => "九合天下",
      :no_races => true,
      :no_professions => true,
      :description => "3D大型第一人称射击角色扮演游戏")
    gameno157.tag_list = "热血, 战争, 道具收费, 第一人称,射击, 3D"
    gameno158 = Game.create(
      :name => "QQ幻想世界",
      :official_web => "http://hxsj.qq.com/",
      :sale_date => "",
      :company => "腾讯",
      :agent => "腾讯",
      :no_races => true,
      :description => "2D大型角色扮演游戏")
    gameno158.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno159 = Game.create(
      :name => "欢乐君主",
      :official_web => "http://www.newhljz.cn/",
      :sale_date => "2007-10-29",
      :company => "Ndoors",
      :agent => "联众世界",
      :no_races => true,
      :no_professions => true,
      :description => "Q版3D大型角色扮演游戏")
    gameno159.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 3D"
    gameno160 = Game.create(
      :name => "海战集结号",
      :official_web => "http://hz.zifugame.com/",
      :sale_date => "2009-6-5",
      :company => "紫府网络科技",
      :agent => "紫府网络科技",
      :no_races => true,
      :no_professions => true,
      :description => "3D第三人称射击角色扮演游戏")
    gameno160.tag_list = "热血, 海战, 道具收费, 第三人称, 射击, 3D"
    gameno161 = Game.create(
      :name => "火力风暴",
      :official_web => "http://fs.ferrygame.com/",
      :sale_date => "2009-10-272009-10-27",
      :company => "渡口网络",
      :agent => "渡口网络",
      :no_races => true,
      :no_professions => true,
      :description => "3D第三人称射击角色扮演游戏")
    gameno161.tag_list = "热血, 仿真, 道具收费, 第三人称, 射击, 3D"
    gameno162 = Game.create(
      :name => "冰风传奇",
      :official_web => "http://dr.sanle.net/index.asp?nfw=101",
      :sale_date => "2001-12-25",
      :company => "Wizgate",
      :agent => "一起玩网络",
      :no_races => true,
      :no_professions => true,
      :description => "2D大型角色扮演游戏")
    gameno162.tag_list = "热血, 科幻, 道具收费, 即时战斗, 2D"
    gameno163 = Game.create(
      :name => "九鼎",
      :official_web => "http://www.herogame.cn/",
      :sale_date => "2006-11-1",
      :company => "逸海情天",
      :agent => "网乐互联",
      :no_races => true,
      :description => "2D大型武侠角色扮演游戏")
    gameno163.tag_list = "热血, 武侠, 道具收费, 即时战斗, 2D"
    gameno164 = Game.create(
      :name => "剑仙",
      :official_web => "http://jx.changyou.com/",
      :sale_date => "2009-8-18",
      :company => "搜狐畅游",
      :agent => "搜狐畅游",
      :no_races => true,
      :description => "2D大型角色扮演游戏")
    gameno164.tag_list = "热血, 中国玄幻, 道具收费, 即时战斗, 2D"
    gameno165 = Game.create(
      :name => "剑舞江南",
      :official_web => "http://jw.zhaouc.net/",
      :sale_date => "2008-9-29",
      :company => "壮游科技",
      :agent => "壮游科技",
      :no_races => true,
      :description => "2D大型角色扮演游戏")
    gameno165.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno166 = Game.create(
      :name => "金庸群侠传online",
      :official_web => "http://jy.online-game.com.cn/",
      :sale_date => "2002-5-20",
      :company => "游龙在线",
      :agent => "龙图智库",
      :no_races => true,
      :description => "2D半即使制角色扮演游戏")
    gameno166.tag_list = "热血, 武侠, 道具收费, 时间收费, 半即时战斗, 2D"
    gameno167 = Game.create(
      :name => "惊天动地",
      :official_web => "http://cabal.moliyo.com/index.html",
      :sale_date => "2006-12-25",
      :company => "韩国ESTsoft",
      :agent => "摩力游",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno167.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno168 = Game.create(
      :name => "劲爆篮球",
      :official_web => "http://lq.9you.com/web_v2/",
      :sale_date => "2009-9-17",
      :company => "久游",
      :agent => "久游",
      :no_races => true,
      :description => "3D篮球休闲游戏")
    gameno168.tag_list = "轻松, 篮球, 道具收费, 休闲, 3D"
    gameno169 = Game.create(
      :name => "机战",
      :official_web => "http://jz.91.com/",
      :sale_date => "2007-4-25",
      :company => "天晴数码",
      :agent => "网龙",
      :no_races => true,
      :no_professions => true,
      :description => "3D机战类角色扮演游戏")
    gameno169.tag_list = "热血, 机战, 道具收费, 即时战斗, 3D"
    gameno170 = Game.create(
      :name => "九洲英雄",
      :official_web => "http://hero.online-game.com.cn/",
      :sale_date => "2007-3-27",
      :company => "龙图智库",
      :agent => "龙图智库",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno170.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno171 = Game.create(
      :name => "精灵复兴",
      :official_web => "http://pt.yetime.cn/",
      :sale_date => "2006-9-29",
      :company => "艺堂娱乐",
      :agent => "易当网络",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno171.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno172 = Game.create(
      :name => "劲爆足球",
      :official_web => "http://soccer.9you.com",
      :sale_date => "2006-11-30",
      :company => "SonicAn",
      :agent => "久游",
      :no_races => true,
      :description => "3D足球角色扮演游戏")
    gameno172.tag_list = "热血, 休闲, 道具收费, 足球, 3D"
    gameno173 = Game.create(
      :name => "极限飚车",
      :official_web => "http://lr.joyzone.com.cn/",
      :sale_date => "2009-6-25",
      :company => "Invictus",
      :agent => "天纵",
      :no_races => true,
      :no_professions => true,
      :description => "3D赛车竞速游戏")
    gameno173.tag_list = "仿真, 轻松, 道具收费, 竞速, 3D"
    gameno174 = Game.create(
      :name => "极道车神",
      :official_web => "http://cs.playcool.com/",
      :sale_date => "2007-12-5",
      :company => "冰动娱乐",
      :agent => "冰动娱乐",
      :no_races => true,
      :no_professions => true,
      :stop_running => true,
      :description => "3D赛车竞速游戏")
    gameno174.tag_list = "Q版, 休闲, 道具收费, 竞速, 3D"
    gameno175 = Game.create(
      :name => "机甲世纪II",
      :official_web => "http://aoa.woniu.com/",
      :sale_date => "2008-5-30",
      :company => "游戏蜗牛",
      :agent => "游戏蜗牛",
      :no_races => true,
      :description => "3D科幻角色扮演游戏")
    gameno175.tag_list = "热血, 科幻, 道具收费, 即时战斗, 3D"
    gameno176 = Game.create(
      :name => "精灵乐章",
      :official_web => "http://dj.gfyoyo.com.cn/",
      :sale_date => "2009-8-13",
      :company => "亿启数码",
      :agent => "悠游网",
      :no_races => true,
      :description => "Q版3D奇幻角色扮演游戏")
    gameno176.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 3D"
    gameno177 = Game.create(
      :name => "抗战",
      :official_web => "http://kz.zqgame.com/",
      :sale_date => "2007-8-4",
      :company => "中青宝网",
      :agent => "中青宝网",
      :no_races => true,
      :description => "2D抗战角色扮演游戏")
    gameno177.tag_list = "热血, 战争, 道具收费, 即时战斗, 2D"
    gameno178 = Game.create(
      :name => "开创世纪",
      :official_web => "http://www.xuetiangame.com/",
      :sale_date => "2009-7-1",
      :company => "雪天网络",
      :agent => "雪天网络",
      :no_races => true,
      :no_professions => true,
      :description => "2D角色扮演游戏")
    gameno178.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno179 = Game.create(
      :name => "KO堂",
      :official_web => "http://ko.ferrygame.com/index.html",
      :sale_date => "2009-6-18",
      :company => "Marvel QUEST",
      :agent => "渡口网络",
      :no_races => true,
      :description => "Q版2D横板角色扮演游戏")
    gameno179.tag_list = "Q版, 奇幻, 道具收费, 横板战斗, 2D"
    gameno180 = Game.create(
      :name => "科洛斯2",
      :official_web => "http://www.cronous.com.cn/index.jsp",
      :sale_date => "2009-2-19",
      :company => "未知",
      :agent => "全向时空",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno180.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno181 = Game.create(
      :name => "龙族",
      :official_web => "",
      :sale_date => "2002-2-22",
      :company => "冰动娱乐",
      :agent => "冰动娱乐",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno181.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno182 = Game.create(
      :name => "鹿鼎记",
      :official_web => "http://ldj.changyou.com/",
      :sale_date => "2008-9-17",
      :company => "搜狐畅游",
      :agent => "搜狐畅游",
      :no_races => true,
      :description => "Q版3D中国玄幻角色扮演游戏")
    gameno182.tag_list = "Q版, 中国玄幻, 道具收费, 即时战斗, 3D"
    gameno183 = Game.create(
      :name => "新龙骑士",
      :official_web => "http://lqs2.passionent.com/",
      :sale_date => "2009-10-16",
      :company => "派讯娱乐",
      :agent => "派讯娱乐",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno183.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno184 = Game.create(
      :name => "灵游记",
      :official_web => "http://www.lyjonline.cn/index.asp?nfw=2",
      :sale_date => "2007-4-18",
      :company => "NNG",
      :agent => "联众世界",
      :no_races => true,
      :stop_running => true,
      :description => "2D横板角色扮演游戏")
    gameno184.tag_list = "Q版, 奇幻, 道具收费, 横板战斗, 2D"
    gameno185 = Game.create(
      :name => "乱武天下",
      :official_web => "http://luan.sdo.com/Project/xinshou/",
      :sale_date => "2009-10-31",
      :company => "中娱在线",
      :agent => "盛大网络",
      :no_races => true,
      :no_professions => true,
      :description => "3D休闲格斗游戏")
    gameno185.tag_list = "Q版, 休闲, 道具收费, 格斗, 3D"
    gameno186 = Game.create(
      :name => "乱世三国",
      :official_web => "http://ls.ourgame.com/index.htm",
      :sale_date => "2007-8-22",
      :company => "TOM游戏",
      :agent => "TOM游戏",
      :no_races => true,
      :description => "2D三国类角色扮演游戏")
    gameno186.tag_list = "热血, 战争, 三国, 道具收费, 即时战斗, 2D"
    gameno187 = Game.create(
      :name => "烈焰飞雪",
      :official_web => "http://ly.18day.com/index/index.aspx",
      :sale_date => "2007-9-30",
      :company => "烈焰飞雪项目组",
      :agent => "台州精业",
      :no_races => true,
      :description => "3D角色扮演游戏")
    gameno187.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno188 = Game.create(
      :name => "流星花园",
      :official_web => "http://lx.5u56.com/",
      :sale_date => "2006-9-8",
      :company => "广东数通",
      :agent => "广东数通",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno188.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno189 = Game.create(
      :name => "天空战记",
      :official_web => "http://sky.sdo.com/web1/door/index.html",
      :sale_date => "2009-3-18",
      :company => "ACTOZ",
      :agent => "盛大网络",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno189.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno190 = Game.create(
      :name => "龙神传说",
      :official_web => "http://act.ls.sdo.com/project/20081219/index.htm",
      :sale_date => "2008-4-2",
      :company => "盛大网络",
      :agent => "盛大网络",
      :no_races => true,
      :description => "Q版2D奇幻角色扮演游戏")
    gameno190.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 2D"
    gameno191 = Game.create(
      :name => "路尼亚战记",
      :official_web => "http://lunia.gtgame.com.cn/",
      :sale_date => "2009-2-27",
      :company => "韩国Allm",
      :agent => "中华网",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno191.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno192 = Game.create(
      :name => "恋爱盒子",
      :official_web => "http://love.online-game.com.cn/",
      :sale_date => "2006-8-30",
      :company => "龙图智库",
      :agent => "游龙在线",
      :no_races => true,
      :no_professions => true,
      :description => "2D恋爱养成网络游戏")
    gameno192.tag_list = "Q版, 时间收费, 道具收费, 养成, 2D"
    gameno193 = Game.create(
      :name => "炼狱online",
      :official_web => "http://www.lianyu.com/index.html",
      :sale_date => "2009-9-29",
      :company => "海之童",
      :agent => "百游",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno193.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno194 = Game.create(
      :name => "乱世英杰",
      :official_web => "http://ls.fu16.com/",
      :sale_date => "2008-12-25",
      :company => "非游娱乐",
      :agent => "非游娱乐",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno194.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno195 = Game.create(
      :name => "亮剑",
      :official_web => "http://lj.zqgame.com/",
      :sale_date => "2009-08-15",
      :company => "中青宝网",
      :agent => "中青宝网",
      :no_races => true,
      :description => "3D历史战争角色扮演游戏")
    gameno195.tag_list = "热血, 历史, 战争, 道具收费, 即时战斗, 3D"
    gameno196 = Game.create(
      :name => "绿色征途",
      :official_web => "http://ls.ztgame.com/",
      :sale_date => "2009-10-23",
      :company => "巨人网络",
      :agent => "巨人网络",
      :no_races => true,
      :description => "3D角色扮演游戏")
    gameno196.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno197 = Game.create(
      :name => "龙",
      :official_web => "http://www.loong3d.com",
      :sale_date => "2009-10-28",
      :company => "大承网络",
      :agent => "大承网络",
      :no_races => true,
      :no_professions => true,
      :description => "3D奇幻角色扮演游戏")
    gameno197.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno198 = Game.create(
      :name => "六脉神剑",
      :official_web => "http://www.6msj.com/",
      :sale_date => "2009-7-15",
      :company => "目标软件",
      :agent => "神雕网络",
      :no_races => true,
      :description => "3D角色扮演游戏")
    gameno198.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno199 = Game.create(
      :name => "墨香online",
      :official_web => "http://ms.runup.cn/top.php",
      :sale_date => "2008-11-20",
      :company => "EYA(韩国)",
      :agent => "千峰云起",
      :no_races => true,
      :no_professions => true,
      :description => "2D武侠角色扮演游戏")
    gameno199.tag_list = "热血, 武侠, 道具收费, 即时战斗, 2D"
    gameno200 = Game.create(
      :name => "猛将online",
      :official_web => "http://mj.9you.com",
      :sale_date => "",
      :company => "久游网",
      :agent => "久游网",
      :stop_running => true,
      :description => "2D三国类角色扮演网络游戏")
    gameno200.tag_list = "热血, 三国, 奇幻, 道具收费, 即时战斗, 2D"
    gameno201 = Game.create(
      :name => "美丽世界",
      :official_web => "http://home.nage.com.cn/",
      :sale_date => "2003-6-18",
      :company => "韩国eSofnet",
      :agent => "清华同方",
      :no_races => true,
      :no_professions => true,
      :description => "3D青春角色扮演游戏")
    gameno201.tag_list = "青春, 仿真, 道具收费, 养成, 3D"
    gameno202 = Game.create(
      :name => "梦幻龙族",
      :official_web => "http://ml.playcool.com/",
      :sale_date => "2009-2-26",
      :company => "barunson",
      :agent => "冰动娱乐",
      :no_races => true,
      :description => "Q版3D角色扮演游戏")
    gameno202.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno203 = Game.create(
      :name => "梦幻国度",
      :official_web => "http://home.mland.sdo.com/2006/newguide/minisite/index.htm",
      :sale_date => "2005-4-29",
      :company => "盛大网络",
      :agent => "盛大网络",
      :no_races => true,
      :no_professions => true,
      :description => "Q版2D角色扮演游戏")
    gameno203.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 2D"
    gameno204 = Game.create(
      :name => "魔力宝贝",
      :official_web => "http://www.crossgate.com.cn/main.html",
      :sale_date => "2002-3-30",
      :company => "ENIX",
      :agent => "易玩通",
      :no_races => true,
      :description => "2D回合制角色扮演游戏")
    gameno204.tag_list = "Q版, 奇幻, 时间收费, 回合制战斗, 2D"
    gameno205 = Game.create(
      :name => "猛将传online",
      :official_web => "http://mjz.xyygame.com/",
      :sale_date => "2007-10-18",
      :company => "贝海网络",
      :agent => "贝海网络",
      :no_races => true,
      :description => "2D横板角色扮演游戏")
    gameno205.tag_list = "热血, 奇幻, 道具收费, 横板战斗, 2D"
    gameno206 = Game.create(
      :name => "魔神争霸",
      :official_web => "http://ms.ferrygame.com/default.aspx",
      :sale_date => "2008-10-10",
      :company => "渡口科技",
      :agent => "渡口科技",
      :no_races => true,
      :description => "3D奇幻回合制网游")
    gameno206.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno207 = Game.create(
      :name => "梦幻古龙",
      :official_web => "http://mg.51hit.com/",
      :sale_date => "2009-5-22",
      :company => "泰傲&智傲",
      :agent => "深圳泰傲",
      :no_races => true,
      :description => "3D角色扮演游戏")
    gameno207.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 3D"
    gameno208 = Game.create(
      :name => "魔咒",
      :official_web => "http://mz.woyou.net/",
      :sale_date => "2009-9-15",
      :company => "亚米多",
      :agent => "易通达",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno208.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno209 = Game.create(
      :name => "梦想岛",
      :official_web => "",
      :sale_date => "2009-6-8",
      :company => "天盟数码",
      :agent => "天盟数码",
      :no_races => true,
      :description => "Q版3D横板角色扮演游戏")
    gameno209.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 3D"
    gameno210 = Game.create(
      :name => "梦幻迪士尼",
      :official_web => "http://dsn.91.com/",
      :sale_date => "2009-9-29",
      :company => "网龙公司",
      :agent => "网龙公司",
      :no_races => true,
      :description => "Q版3D回合制角色扮演游戏")
    gameno210.tag_list = "Q版, 奇幻, 道具收费, 回合制战斗, 3D"
    gameno211 = Game.create(
      :name => "魔幻盛典",
      :official_web => "http://ra.moliyo.com/",
      :sale_date => "2008-5-22",
      :company => "摩力游",
      :agent => "摩力游",
      :no_races => true,
      :description => "3D角色扮演游戏")
    gameno211.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno212 = Game.create(
      :name => "名将",
      :official_web => "http://mj.8zgame.com/main.aspx",
      :sale_date => "2009-6-13",
      :company => "八泽科技",
      :agent => "八泽科技",
      :no_races => true,
      :description => "2D中国玄幻角色扮演游戏")
    gameno212.tag_list = "热血, 中国玄幻, 道具收费, 即时战斗, 2D"
    gameno213 = Game.create(
      :name => "名将三国",
      :official_web => "http://wof.the9.com/",
      :sale_date => "2009-8-10",
      :company => "第九城市",
      :agent => "第九城市",
      :no_races => true,
      :description => "2D横板角色扮演游戏")
    gameno213.tag_list = "热血, 中国玄幻, 道具收费, 横板战斗, 2D"
    gameno214 = Game.create(
      :name => "梦幻星球",
      :official_web => "http://ru.cdcgames.net/",
      :sale_date => "",
      :company => "CDCGAMES",
      :agent => "北京软星",
      :no_races => true,
      :description => "3D半即时回合制角色扮演游戏")
    gameno214.tag_list = "Q版, 奇幻, 道具收费, 半即时战斗, 3D"
    gameno215 = Game.create(
      :name => "MKZ军魂",
      :official_web => "http://mkz.175pt.com/",
      :sale_date => "2009-9-7",
      :company => "目标软件",
      :agent => "175平台",
      :no_races => true,
      :no_professions => true,
      :description => "3D第一人称射击游戏")
    gameno215.tag_list = "热血, 第一人称, 道具收费, 射击, 3D"
    gameno216 = Game.create(
      :name => "NBA STREET Online",
      :official_web => "http://www.nbaso.com/",
      :sale_date => "2008-12-19",
      :company => "EA Sport",
      :agent => "天游",
      :no_races => true,
      :no_professions => true,
      :description => "3D休闲篮球游戏")
    gameno216.tag_list = "休闲, 竞技, 道具收费, 篮球, 3D"
    gameno217 = Game.create(
      :name => "破天一剑",
      :official_web => "http://www.pcikchina.com/",
      :sale_date => "2007-6-5",
      :company => "MAGICS",
      :agent => "北京伙聚",
      :no_races => true,
      :no_professions => true,
      :description => "2D角色扮演游戏")
    gameno217.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno218 = Game.create(
      :name => "炮炮火枪手",
      :official_web => "http://www.popshot.com.cn/",
      :sale_date => "2007-7-10",
      :company => "世纪天成",
      :agent => "世纪天成",
      :no_races => true,
      :no_professions => true,
      :stop_running => true,
      :description => "2D休闲射击类网游")
    gameno218.tag_list = "Q版, 休闲, 道具收费, 射击, 2D"
    gameno219 = Game.create(
      :name => "拍拍部落",
      :official_web => "http://www.paipaijoy.com/",
      :sale_date => "2007-8-28",
      :company => "天游软件",
      :agent => "天游软件",
      :no_races => true,
      :no_professions => true,
      :description => "3D休闲网球养成游戏")
    gameno219.tag_list = "Q版, 休闲, 道具收费, 网球, 养成, 3D"
    gameno220 = Game.create(
      :name => "飘邈之旅",
      :official_web => "http://pm.gfyoyo.com.cn/",
      :sale_date => "2009-7-15",
      :company => "智冠电子",
      :agent => "悠游网",
      :no_races => true,
      :description => "3D中国玄幻角色扮演游戏")
    gameno220.tag_list = "热血, 中国玄幻, 道具收费, 即时战斗, 3D"
    gameno221 = Game.create(
      :name => "七龙珠online",
      :official_web => "",
      :sale_date => "",
      :company => "Ntl-inc",
      :agent => "",
      :no_races => true,
      :no_professions => true,
      :description => "3D角色扮演游戏")
    gameno221.tag_list = "热血, 奇幻, 七龙珠, 即时战斗, 3D"
    gameno222 = Game.create(
      :name => "千秋",
      :official_web => "http://qq.zqgame.com/",
      :sale_date => "2009-7-10",
      :company => "中青宝网",
      :agent => "中青宝网",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno222.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno223 = Game.create(
      :name => "圈圈大冒险",
      :official_web => "http://dmx.yxqz.com/default.shtml?source=dmx_173",
      :sale_date => "2009-4-25",
      :company => "厦门奇域科技",
      :agent => "广州畅游",
      :no_races => true,
      :description => "Q版2D回合制角色扮演游戏")
    gameno223.tag_list = "Q版, 奇幻, 道具收费, 回合制战斗, 2D"
    gameno224 = Game.create(
      :name => "群英赋",
      :official_web => "http://www.qyfonline.com/",
      :sale_date => "",
      :company => "光涛互动",
      :agent => "联众公司",
      :no_races => true,
      :no_professions => true,
      :description => "3D三国类角色扮演游戏")
    gameno224.tag_list = "热血, 奇幻, 三国, 即时战斗, 3D"
    gameno225 = Game.create(
      :name => "秦伤",
      :official_web => "http://qs.zhaouc.net/",
      :sale_date => "2009-9-12",
      :company => "目标软件",
      :agent => "目标软件",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno225.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno226 = Game.create(
      :name => "RF2.0星球大战",
      :official_web => "http://rf2.5u56.com/main.html",
      :sale_date => "2008-10-30",
      :company => "韩国CCR",
      :agent => "我游我乐",
      :no_races => true,
      :description => "3D星战角色扮演游戏")
    gameno226.tag_list = "热血, 星战, 道具收费, 即时战斗, 3D"
    gameno227 = Game.create(
      :name => "仙境传说2(RO2)",
      :official_web => "http://www.ro2china.cn/",
      :sale_date => "",
      :company => "Gravity",
      :agent => "第九城市",
      :no_races => true,
      :description => "3D角色扮演游戏")
    gameno227.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno228 = Game.create(
      :name => "如来神掌online",
      :official_web => "http://www.rulaionline.com/",
      :sale_date => "2007-8-18",
      :company => "游戏米果",
      :agent => "游戏米果",
      :no_races => true,
      :description => "3D奇幻回合制角色扮演网游")
    gameno228.tag_list = "热血, 奇幻, 道具收费, 回合制战斗, 3D"
    gameno229 = Game.create(
      :name => "热血英豪",
      :official_web => "http://bfo.sdo.com/Web2.0/home/",
      :sale_date => "2002-4-23",
      :company => "盛大网络",
      :agent => "盛大网络",
      :no_races => true,
      :no_professions => true,
      :description => "2D休闲格斗游戏")
    gameno229.tag_list = "热血, 休闲, 道具收费, 格斗, 2D"
    gameno230 = Game.create(
      :name => "如来丢丢球",
      :official_web => "www.rulaionline.com",
      :sale_date => "2007-8-9",
      :company => "九冠数码",
      :agent => "游戏米果",
      :no_races => true,
      :no_professions => true,
      :description => "3D运动休闲游戏")
    gameno230.tag_list = "Q版, 运动, 道具收费, 休闲, 3D"
    gameno231 = Game.create(
      :name => "冲锋online(RUSH)",
      :official_web => "http://www.rushcn.com/",
      :sale_date => "2007-7-20",
      :company => "softnyx",
      :agent => "戏杰环球",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno231.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno232 = Game.create(
      :name => "人生online",
      :official_web => "http://www.hi365.com/",
      :sale_date => "2009-10-30",
      :company => "扬博网络",
      :agent => "扬博网络",
      :no_races => true,
      :no_professions => true,
      :description => "3D养成角色扮演游戏")
    gameno232.tag_list = "热血, 仿真, 道具收费, 养成, 3D"
    gameno233 = Game.create(
      :name => "三国征战online",
      :official_web => "http://www.baiyou100.com/",
      :sale_date => "2008-9-16",
      :company => "日本世嘉",
      :agent => "百游",
      :no_races => true,
      :no_professions => true,
      :description => "3D三国类策略游戏")
    gameno233.tag_list = "热血, 三国, 道具收费, 策略, 3D"
    gameno234 = Game.create(
      :name => "丝路传说",
      :official_web => "http://www.srocn.com/cover_new/cover071205/index.htm",
      :sale_date => "2008-4-2",
      :company => "韩国JOYMAX",
      :agent => "北京世模科技",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno234.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno235 = Game.create(
      :name => "十面埋伏online",
      :official_web => "mf.t2cn.com",
      :sale_date => "2007-12-21",
      :company => "天游软件",
      :agent => "天游软件",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno235.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno236 = Game.create(
      :name => "三国演义Online",
      :official_web => "http://sg.online-game.com.cn/",
      :sale_date => "2005-7-16",
      :company => "智冠",
      :agent => "游龙在线",
      :no_races => true,
      :description => "2D三国类角色扮演游戏")
    gameno236.tag_list = "热血, 三国, 道具收费, 即时战斗, 2D"
    gameno237 = Game.create(
      :name => "神将",
      :official_web => "http://sj.ferrygame.com/page/index.aspx",
      :sale_date => "2009-10-22",
      :company => "渡口网络",
      :agent => "渡口网络",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno237.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno238 = Game.create(
      :name => "圣斗士OL",
      :official_web => "http://www.sds1.cn/",
      :sale_date => "2009-6-20",
      :company => "成都梦工厂",
      :agent => "成都梦工厂",
      :no_races => true,
      :description => "3D角色扮演游戏")
    gameno238.tag_list = "热血, 圣斗士, 道具收费, 即时战斗, 3D"
    gameno239 = Game.create(
      :name => "蜀山OL",
      :official_web => "http://ss.mop.com/",
      :sale_date => "2007-12-12",
      :company => "千橡互动",
      :agent => "猫扑网",
      :no_races => true,
      :description => "3D中国玄幻角色扮演游戏")
    gameno239.tag_list = "热血, 中国玄幻, 道具收费, 即时战斗, 3D"
    gameno240 = Game.create(
      :name => "三国志OL",
      :official_web => "http://sol.playcool.com/",
      :sale_date => "",
      :company => "日本光荣 ",
      :agent => "上海冰动娱乐",
      :no_races => true,
      :no_professions => true,
      :description => "3D三国类角色扮演游戏")
    gameno240.tag_list = "热血, 三国, 即时战斗, 3D"
    gameno241 = Game.create(
      :name => "生肖外传",
      :official_web => "http://www.12ha.com/",
      :sale_date => "2009-10-23",
      :company => "金酷游戏",
      :agent => "金酷游戏",
      :no_races => true,
      :description => "Q版3D回合制角色扮演游戏")
    gameno241.tag_list = "Q版, 中国玄幻, 道具收费, 回合制战斗, 3D"
    gameno242 = Game.create(
      :name => "生死格斗Online",
      :official_web => "http://doa.sdo.com/web3/homing/default.htm",
      :sale_date => "2008-8-22",
      :company => "TECMO",
      :agent => "盛大网络",
      :no_races => true,
      :no_professions => true,
      :description => "3D格斗网游")
    gameno242.tag_list = "热血, 竞技, 道具收费, 格斗, 3D"
    gameno243 = Game.create(
      :name => "时空之泪",
      :official_web => "www.gdsonline.cn",
      :sale_date => "2007-10-12",
      :company => "盛科网络",
      :agent => "盛科网络",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno243.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno244 = Game.create(
      :name => "三国群英传",
      :official_web => "http://sg.iyoyo.com.cn/index.aspx",
      :sale_date => "2005-9-15",
      :company => "奧汀科技",
      :agent => "悠游网",
      :no_races => true,
      :description => "3D三国类角色扮演游戏")
    gameno244.tag_list = "热血, 三国, 时间收费, 道具收费, 横板策略战斗, 3D"
    gameno245 = Game.create(
      :name => "圣灵传说",
      :official_web => "http://www.sns52.com/",
      :sale_date => "2009-4-15",
      :company => "韩国DNC",
      :agent => "游艺春秋",
      :no_races => true,
      :description => "Q版3D奇幻角色扮演游戏")
    gameno245.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 3D"
    gameno246 = Game.create(
      :name => "神兽",
      :official_web => "http://ss.linekong.com/",
      :sale_date => "2009-8-14",
      :company => "奇域",
      :agent => "蓝港在线",
      :no_races => true,
      :description => "3D回合制角色扮演游戏")
    gameno246.tag_list = "Q版, 奇幻, 道具收费, 回合制战斗, 3D"
    gameno247 = Game.create(
      :name => "盛世OL",
      :official_web => "http://www.shengol.com/",
      :sale_date => "2009-5-28",
      :company => "暴雨信息科技",
      :agent => "暴雨信息科技",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno247.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno248 = Game.create(
      :name => "蜀山新传",
      :official_web => "http://ss.sdo.com/web1/intro/index.htm",
      :sale_date => "2009-8-7",
      :company => "御风行",
      :agent => "盛大网络",
      :no_races => true,
      :description => "3D中国玄幻角色扮演游戏")
    gameno248.tag_list = "热血, 中国玄幻, 道具收费, 即时战斗, 3D"
    gameno249 = Game.create(
      :name => "三国鼎立",
      :official_web => "http://www.sanguochina.com/",
      :sale_date => "",
      :company => "龙图智库",
      :agent => "风云网络",
      :no_races => true,
      :description => "2D战棋策略类角色扮演游戏")
    gameno249.tag_list = "热血, 三国, 道具收费, 战棋策略, 2D"
    gameno250 = Game.create(
      :name => "天道online",
      :official_web => "http://td.zqgame.com/IndexMain.aspx",
      :sale_date => "2008-7-25",
      :company => "中青宝网",
      :agent => "中青宝网",
      :no_races => true,
      :description => "2D角色扮演游戏")
    gameno250.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno251 = Game.create(
      :name => "探索Online",
      :official_web => "http://ts.wulitou.com/",
      :sale_date => "2008-12-10",
      :company => "百海",
      :agent => "北之辰",
      :no_races => true,
      :no_professions => true,
      :description => "3D航海类角色扮演游戏")
    gameno251.tag_list = "热血, 航海, 道具收费, 即时战斗, 3D"
    gameno252 = Game.create(
      :name => "特勤队",
      :official_web => "http://tqd.17dian.cn/main.htm",
      :sale_date => "2008-1-18",
      :company => "Sidus",
      :agent => "上海志信",
      :no_races => true,
      :no_professions => true,
      :stop_running => true,
      :description => "2D射击休闲游戏")
    gameno252.tag_list = "Q版, 休闲, 道具收费, 射击, 2D"
    gameno253 = Game.create(
      :name => "投名状Online",
      :official_web => "http://tmz.91.com/index/",
      :sale_date => "2007-12-13",
      :company => "天晴数码",
      :agent => "网龙",
      :no_races => true,
      :description => "2D武侠角色扮演游戏")
    gameno253.tag_list = "热血, 武侠, 道具收费, 即时战斗, 2D"
    gameno254 = Game.create(
      :name => "踢踢球",
      :official_web => "ttq.joyzone.com.cn",
      :sale_date => "2007-7-26",
      :company => "东星软件",
      :agent => "天纵网络",
      :no_races => true,
      :no_professions => true,
      :description => "Q版3D足球休闲游戏")
    gameno254.tag_list = "Q版, 休闲, 道具收费, 足球, 3D"
    gameno255 = Game.create(
      :name => "天使之恋Online",
      :official_web => "http://ts.iyoyo.com.cn/",
      :sale_date => "2006-10-27",
      :company => "宇峻奥汀",
      :agent => "悠游网",
      :description => "Q版3D奇幻角色扮演游戏")
    gameno255.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 3D"
    gameno256 = Game.create(
      :name => "天书奇谈",
      :official_web => "http://t.mop.com/",
      :sale_date => "2008-7-15",
      :company => "猫扑",
      :agent => "猫扑",
      :no_races => true,
      :description => "3D奇幻回合制角色扮演游戏")
    gameno256.tag_list = "Q版, 奇幻, 道具收费, 回合制战斗, 3D"
    gameno257 = Game.create(
      :name => "天源4951",
      :official_web => "http://4591.outpop.com/",
      :sale_date => "2009-5-19",
      :company => "同风数码科技",
      :agent => "同风数码科技",
      :no_races => true,
      :description => "3D科幻第一人称射击角色扮演游戏")
    gameno257.tag_list = "热血, 科幻, 第一人称, 道具收费, 射击, 3D"
    gameno258 = Game.create(
      :name => "体育帝国",
      :official_web => "http://eos.ztgame.com/",
      :sale_date => "2009-3-9",
      :company => "Empire of Sports",
      :agent => "巨人网络",
      :no_races => true,
      :no_professions => true,
      :description => "3D体育休闲游戏")
    gameno258.tag_list = "热血, 休闲, 道具收费, 体育, 3D"
    gameno259 = Game.create(
      :name => "Dekaron",
      :official_web => "http://www.dkonline.com.cn/games/dk/intro.htm",
      :sale_date => "2007-4-27",
      :company => "韩国gamehi",
      :agent => "上海盟邦",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno259.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno260 = Game.create(
      :name => "突袭",
      :official_web => "http://www.tuxi.com.cn/",
      :sale_date => "2007-9-6",
      :company => "GameHi",
      :agent => "神州奥美",
      :no_races => true,
      :no_professions => true,
      :description => "3D第一人称射击游戏")
    gameno260.tag_list = "热血, 战争, 道具收费, 第一人称, 射击, 3D"
    gameno261 = Game.create(
      :name => "天骄2活力版",
      :official_web => "http://tjpk.object.com.cn/",
      :sale_date => "2007-5-23",
      :company => "目标在线",
      :agent => "目标在线",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno261.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno262 = Game.create(
      :name => "推推侠",
      :official_web => "http://ttx.sdo.com/web2.0/homepage.htm",
      :sale_date => "2007-8-2",
      :company => "盛大网络",
      :agent => "盛大网络",
      :no_races => true,
      :no_professions => true,
      :description => "2D炸弹人式休闲扮演游戏")
    gameno262.tag_list = "Q版, 休闲, 道具收费, 炸弹人, 2D"
    gameno263 = Game.create(
      :name => "铁血三国志",
      :official_web => "http://sg.xoyo.com/",
      :sale_date => "",
      :company => "金山西山居",
      :agent => "金山西山居",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno263.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno264 = Game.create(
      :name => "天上人间",
      :official_web => "http://www.moliyo.com/",
      :sale_date => "2007-6-22",
      :company => "摩力游",
      :agent => "摩力游",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno264.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno265 = Game.create(
      :name => "特种部队",
      :official_web => "http://sf.17game.com/index.php",
      :sale_date => "2007-6-20",
      :company => "Dragonfly",
      :agent => "17GAME",
      :no_races => true,
      :no_professions => true,
      :description => "3D第一人称射击游戏")
    gameno265.tag_list = "热血, 第一人称, 道具收费, 射击, 3D"
    gameno266 = Game.create(
      :name => "天之游侠",
      :official_web => "http://u.t2uu.com/",
      :sale_date => "2004-12-28",
      :company => "上海天游",
      :agent => "上海天游",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno266.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno267 = Game.create(
      :name => "天涯",
      :official_web => "http://ty.yxfw.com/",
      :sale_date => "2009-10-30",
      :company => "烈焰网络",
      :agent => "烈焰网络",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno267.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno268 = Game.create(
      :name => "问道",
      :official_web => "http://wd.gyyx.cn/index_wd.aspx",
      :sale_date => "2006-4-22",
      :company => "吉比特",
      :agent => "光宇华夏",
      :no_races => true,
      :description => "Q版2D回合制奇幻角色扮演游戏")
    gameno268.tag_list = "Q版, 奇幻, 道具收费, 回合制战斗, 2D"
    gameno269 = Game.create(
      :name => "问鼎",
      :official_web => "http://hero.linekong.com/",
      :sale_date => "2009-6-25",
      :company => "吉比特",
      :agent => "蓝港",
      :no_races => true,
      :no_professions => true,
      :description => "2D奇幻回合制角色扮演游戏")
    gameno269.tag_list = "热血, 奇幻, 道具收费, 回合制战斗, 2D"
    gameno270 = Game.create(
      :name => "唯舞独尊",
      :official_web => "http://www.we5.com.cn/",
      :sale_date => "2008-1-23",
      :company => "鈊象电子",
      :agent => "宏象网络",
      :no_races => true,
      :no_professions => true,
      :description => "3D音乐休闲游戏")
    gameno270.tag_list = "休闲, 音乐, 道具收费, 休闲, 舞蹈, 3D"
    gameno271 = Game.create(
      :name => "王者之印",
      :official_web => "http://wz.9mud.com/",
      :sale_date => "2008-10-10",
      :company => "古虎数码",
      :agent => "古虎数码",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno271.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno272 = Game.create(
      :name => "武易",
      :official_web => "http://wy.521g.com/",
      :sale_date => "2009-8-7",
      :company => "武易网络",
      :agent => "武易网络",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno272.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno273 = Game.create(
      :name => "万王之王3 ",
      :official_web => "http://kok3.ztgame.com/",
      :sale_date => "2009-10-15",
      :company => "巨人网络",
      :agent => "巨人网络",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno273.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno274 = Game.create(
      :name => "问天online",
      :official_web => "http://wt.skdaren.com/",
      :sale_date => "2009-9-30",
      :company => "盛科",
      :agent => "盛科",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno274.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno275 = Game.create(
      :name => "我的小傻瓜",
      :official_web => "http://www.xiaoshagua.com/",
      :sale_date => "2008-9-17",
      :company => "云雀软件",
      :agent => "巨人网络",
      :no_races => true,
      :no_professions => true,
      :description => "2D桌面宠物休闲网游")
    gameno275.tag_list = "Q版, 休闲, 道具收费, 宠物, 养成, 2D"
    gameno276 = Game.create(
      :name => "王者",
      :official_web => "http://king.8760.cn/",
      :sale_date => "2009-7-7",
      :company => "8760网络",
      :agent => "8760网络",
      :no_races => true,
      :no_professions => true,
      :description => "2D奇幻角色扮演游戏")
    gameno276.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno277 = Game.create(
      :name => "新魔界",
      :official_web => "http://www.mwo.cn/",
      :sale_date => "2007-11-28",
      :company => "金酷游戏",
      :agent => "金酷游戏",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno277.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno278 = Game.create(
      :name => "侠义道",
      :official_web => "http://www.xiayidao.cn/",
      :sale_date => "2004-11-18",
      :company => "成都梦工厂",
      :agent => "成都梦工厂",
      :no_races => true,
      :description => "2D武侠角色扮演游戏")
    gameno278.tag_list = "热血, 武侠, 时间收费, 道具收费, 即时战斗, 2D"
    gameno279 = Game.create(
      :name => "新侠义道",
      :official_web => "http://new.xiayidao.cn/Index.html",
      :sale_date => "2008-12-18",
      :company => "成都梦工厂",
      :agent => "成都梦工厂",
      :no_races => true,
      :description => "3D武侠角色扮演游戏")
    gameno279.tag_list = "热血, 武侠, 道具收费, 即时战斗, 3D"
    gameno280 = Game.create(
      :name => "侠义道Ⅱ",
      :official_web => "http://www.xyd2.com.cn/",
      :sale_date => "",
      :company => "成都梦工厂",
      :agent => "TOM网",
      :no_races => true,
      :description => "2D武侠角色扮演游戏")
    gameno280.tag_list = "热血, 武侠, 道具收费, 即时战斗, 2D"
    gameno281 = Game.create(
      :name => "仙侣奇缘",
      :official_web => "http://www.xlqy.net/index.html",
      :sale_date => "2004-11-5",
      :company => "游戏巅峰",
      :agent => "连邦软件",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno281.tag_list = "热血, 奇幻, 时间收费, 即时战斗, 2D"
    gameno282 = Game.create(
      :name => "仙侣奇缘2",
      :official_web => "http://xl2.xoyo.com/",
      :sale_date => "2006-9-25",
      :company => "巅峰软件",
      :agent => "金山西山居",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno282.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno283 = Game.create(
      :name => "新郑和online",
      :official_web => "http://www.xzhonline.com/?connectPath=17173",
      :sale_date => "2006-2-24",
      :company => "欢乐城网络",
      :agent => "欢乐城网络",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno283.tag_list = "热血, 海战, 奇幻, 道具收费, 即时战斗, 3D"
    gameno284 = Game.create(
      :name => "笑闹天宫",
      :official_web => "http://www.juugoo.com/xntg/",
      :sale_date => "2009-4-16",
      :company => "创游软件",
      :agent => "聚购科技",
      :no_races => true,
      :description => "2D中国玄幻回合制角色扮演游戏")
    gameno284.tag_list = "Q版, 中国玄幻, 道具收费, 回合制战斗, 2D"
    gameno285 = Game.create(
      :name => "西游记online",
      :official_web => "http://xy.linekong.com/",
      :sale_date => "2009-9-29",
      :company => "蓝港在线",
      :agent => "蓝港在线",
      :no_races => true,
      :description => "3D中国玄幻角色扮演游戏")
    gameno285.tag_list = "热血, 中国玄幻, 西游记, 道具收费, 即时战斗, 3D"
    gameno286 = Game.create(
      :name => "暇月战歌",
      :official_web => "http://www.tdplay.com.cn/",
      :sale_date => "2009-7-10",
      :company => "目标软件",
      :agent => "目标软件",
      :description => "3D奇幻角色扮演游戏")
    gameno286.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno287 = Game.create(
      :name => "笑傲江湖",
      :official_web => "",
      :sale_date => "",
      :company => "完美时空",
      :agent => "完美时空",
      :no_races => true,
      :description => "3D武侠角色扮演游戏")
    gameno287.tag_list = "热血, 武侠, 即时战斗, 3D"
    gameno288 = Game.create(
      :name => "X-乒乓",
      :official_web => "http://pp.sdo.com/web3/home/index.asp",
      :sale_date => "2007-12-28",
      :company => "盛大网络",
      :agent => "盛大网络",
      :no_races => true,
      :no_professions => true,
      :description => "3D体育休闲网游")
    gameno288.tag_list = "轻松, 休闲, 体育, 道具收费, 乒乓球, 3D"
    gameno289 = Game.create(
      :name => "江湖online",
      :official_web => "http://www.jianghuol.com/",
      :sale_date => "2006-8-6",
      :company => "八八科技",
      :agent => "八八科技",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno289.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno290 = Game.create(
      :name => "仙界传",
      :official_web => "http://www.xjz.com.cn/",
      :sale_date => "2005-6-16",
      :company => "宏象网络",
      :agent => "宏象网络",
      :no_races => true,
      :description => "2D中国玄幻回合制角色扮演游戏")
    gameno290.tag_list = "热血, 中国玄幻, 道具收费, 回合制战斗, 2D"
    gameno291 = Game.create(
      :name => "仙境传说(RO)",
      :official_web => "http://ro.sdo.com/home/homepage.htm",
      :sale_date => "2003-1-1",
      :company => "GRAVITY",
      :agent => "盛大",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno291.tag_list = "Q版, 奇幻, 时间收费, 道具收费, 即时战斗, 2D"
    gameno292 = Game.create(
      :name => "星际家园",
      :official_web => "http://space.fenteng.net/",
      :sale_date => "2004-9-15",
      :company => "纷腾互动数码",
      :agent => "纷腾互动数码",
      :no_races => true,
      :no_professions => true,
      :description => "2D奇幻角色扮演游戏")
    gameno292.tag_list = "热血, 星战, 奇幻, 时间收费, 道具收费, 即时战斗, 2D"
    gameno293 = Game.create(
      :name => "小鱼儿与花无缺",
      :official_web => "http://tth2.iyoyo.com.cn",
      :sale_date => "2006-6-1",
      :company => "悠游网",
      :agent => "悠游网",
      :no_races => true,
      :stop_running => true,
      :description => "Q版2D中国玄幻角色扮演游戏")
    gameno293.tag_list = "Q版, 中国玄幻, 道具收费, 即时战斗, 2D"
    gameno294 = Game.create(
      :name => "星尘传说",
      :official_web => "http://www.star07.com/",
      :sale_date => "2008-12-29",
      :company => "星漫科技",
      :agent => "星漫科技",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno294.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 3D"
    gameno295 = Game.create(
      :name => "逍遥传说",
      :official_web => "http://xy.henhaoji.com/",
      :sale_date => "2009-1-1",
      :company => "金山多益",
      :agent => "金山多益",
      :no_races => true,
      :description => "3D中国玄幻回合制角色扮演游戏")
    gameno295.tag_list = "Q版, 中国玄幻, 时间收费, 即时战斗, 3D"
    gameno296 = Game.create(
      :name => "新密传",
      :official_web => "http://tantra.ccjoy.com/",
      :sale_date => "2009-9-16",
      :company => "韩光公司",
      :agent => "嬉戏族互动娱乐网",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno296.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno297 = Game.create(
      :name => "星际文明",
      :official_web => "http://star.176.com/",
      :sale_date => "2009-8-13",
      :company => "天盟数码",
      :agent => "天盟数码",
      :no_races => true,
      :no_professions => true,
      :description => "3D战争策略游戏")
    gameno297.tag_list = "热血, 战争, 道具收费, 策略, 3D"
    gameno298 = Game.create(
      :name => "仙途",
      :official_web => "http://xt.ztgame.com/",
      :sale_date => "2009-10-30",
      :company => "雪狼软件",
      :agent => "巨人网络",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno298.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno299 = Game.create(
      :name => "英雄岛",
      :official_web => "http://yxd.21mmo.com/",
      :sale_date => "2009-7-10",
      :company => "深圳网域",
      :agent => "深圳网域",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno299.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 2D"
    gameno300 = Game.create(
      :name => "倚天2",
      :official_web => "http://yt2.catv.net/",
      :sale_date => "2007-9-20",
      :company => "中广网",
      :agent => "中广网",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno300.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno301 = Game.create(
      :name => "英雄2",
      :official_web => "http://yx2.forugame.com/",
      :sale_date => "2007-7-29",
      :company => "MGAME",
      :agent => "风云网络",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno301.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno302 = Game.create(
      :name => "炎黄传说",
      :official_web => "http://yh.5u56.com/index.html",
      :sale_date => "2007-11-28",
      :company => "魔方软件",
      :agent => "广东数通",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno302.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno303 = Game.create(
      :name => "倚天剑与屠龙刀",
      :official_web => "http://yt.linekong.com/index1.php",
      :sale_date => "2007-12-26",
      :company => "蓝港在线",
      :agent => "蓝港在线",
      :no_races => true,
      :description => "2D武侠回合制角色扮演游戏")
    gameno303.tag_list = "Q版, 武侠, 道具收费, 即时战斗, 2D"
    gameno304 = Game.create(
      :name => "炎龙骑士团online",
      :official_web => "fdo.iyoyo.com.cn",
      :sale_date => "2007-11-23",
      :company => "汉堂国际",
      :agent => "悠游网",
      :description => "Q版2D奇幻角色扮演游戏")
    gameno304.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 2D"
    gameno305 = Game.create(
      :name => "游戏人生",
      :official_web => "http://rs.wanku.com/",
      :sale_date => "2009-1-16",
      :company => "火石软件",
      :agent => "火石软件",
      :no_races => true,
      :description => "Q版2D奇幻回合制角色扮演游戏")
    gameno305.tag_list = "Q版, 奇幻, 道具收费, 回合制战斗, 2D"
    gameno306 = Game.create(
      :name => "伊苏战记",
      :official_web => "http://ys.10sea.com/index.shtml",
      :sale_date => "2009-2-27",
      :company => "韩国CJI",
      :agent => "上海天希",
      :description => "3D奇幻角色扮演游戏")
    gameno306.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 3D"
    gameno307 = Game.create(
      :name => "勇者传说",
      :official_web => "http://yz.go2game.com/",
      :sale_date => "2009-10-13",
      :company => "广州网游数码",
      :agent => "广州网游数码",
      :no_races => true,
      :description => "2D奇幻回合制角色扮演游戏")
    gameno307.tag_list = "热血, 奇幻, 道具收费, 回合制战斗, 2D"
    gameno308 = Game.create(
      :name => "战火：红色警戒(OL)",
      :official_web => "http://www.fireol.com/",
      :sale_date => "2007-11-16",
      :company => "光联时空",
      :agent => "游诚时代",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno308.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 2D"
    gameno309 = Game.create(
      :name => "征战online",
      :official_web => "http://zz.lyjoy.com/",
      :sale_date => "2008-5-13",
      :company => "风云工作室",
      :agent => "龙游天下",
      :description => "3D三国类奇幻角色扮演游戏")
    gameno309.tag_list = "热血, 奇幻, 三国, 道具收费, 即时战斗, 3D"
    gameno310 = Game.create(
      :name => "指环王OL",
      :official_web => "http://lotro.cdcgames.net/",
      :sale_date => "2009-10-23",
      :company => "Turbine",
      :agent => "CDC Games",
      :description => "3D奇幻角色扮演游戏")
    gameno310.tag_list = "史诗, 奇幻, 道具收费, 即时战斗, 3D"
    gameno311 = Game.create(
      :name => "纸客帝国",
      :official_web => "http://p.qwd1.com/",
      :sale_date => "2007-12-13",
      :company => "趣味第一",
      :agent => "趣味第一",
      :no_races => true,
      :no_professions => true,
      :description => "2D第一人称射击游戏")
    gameno311.tag_list = "休闲, 第一人称, 道具收费, 射击, 2D"
    gameno312 = Game.create(
      :name => "纵横时空",
      :official_web => "http://www.mmochina.com/",
      :sale_date => "2009-4-11",
      :company => "卓智时代",
      :agent => "卓智时代",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno312.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno313 = Game.create(
      :name => "蒸汽幻想",
      :official_web => "http://www.t2ns.com/",
      :sale_date => "2007-3-15",
      :company => "Hanbitsoft",
      :agent => "天游软件",
      :description => "Q版3D奇幻角色扮演游戏")
    gameno313.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 3D"
    gameno314 = Game.create(
      :name => "诸侯",
      :official_web => "http://zh.12ha.com/",
      :sale_date => "2009-7-3",
      :company => "金酷",
      :agent => "金酷",
      :no_races => true,
      :description => "3D奇幻角色扮演游戏")
    gameno314.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno315 = Game.create(
      :name => "众神之战",
      :official_web => "http://zs.176.com/",
      :sale_date => "2009-7-20",
      :company => "天盟数码",
      :agent => "天盟数码",
      :no_races => true,
      :description => "2D奇幻角色扮演游戏")
    gameno315.tag_list = "Q版, 奇幻, 道具收费, 即时战斗, 2D"
    gameno316 = Game.create(
      :name => "战地之王",
      :official_web => "http://ava.qq.com/",
      :sale_date => "2009-6-18",
      :company => "Redduck",
      :agent => "腾讯",
      :no_races => true,
      :no_professions => true,
      :description => "3D第一人称射击游戏")
    gameno316.tag_list = "竞技, 第一人称, 道具收费, 射击, 3D"
    gameno317 = Game.create(
      :name => "暗黑之门：伦敦",
      :official_web => "",
      :sale_date => "2006-2-22",
      :company => "旗舰工作室",
      :agent => "第九城市",
      :no_races => true,
      :description => "欧美3D大型角色扮演游戏")
    gameno317.tag_list = "热血, 奇幻, 道具收费, 即时战斗, 3D"
    gameno318 = Game.create(
      :name => "飚车",
      :official_web => "http://ctr.joyzone.com.cn/",
      :sale_date => "2005-3-18",
      :company => "韩国现代数码娱乐",
      :agent => "天纵网络",
      :no_races => true,
      :no_professions => true,
      :description => "赛车竞速")
    gameno318.tag_list = "热血, 竞技, 赛车, 道具收费, 3D"
    gameno319 = Game.create(
      :name => "精武世界",
      :official_web => "http://www.jingwuonline.com/",
      :sale_date => "2009-6-12",
      :company => "联众世界",
      :agent => "联众世界",
      :no_races => true,
      :no_professions => true,
      :description => "3D在线格斗游戏")
    gameno319.tag_list = "热血, 格斗, 道具收费, 3D"
  end

  def self.down
  end
end
